<a href="https://colab.research.google.com/github/LUCASCAZANE/Proj1_Form_Cont_Caixa_Verso/blob/main/projeto1_formacao_continuada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Pacote para criar marca d'agua imprimindo assim as versões dos pacotes
!pip install -q -U watermark

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 25.8 MB/s eta 0:00:00

In [2]:
# Pacote para visualizar valores ausentes em uma variável
!pip install -q missingno

In [3]:
# Imports
# Primeira dupla para manipulação de dados
import pandas as pd
import numpy as np

# A Segunda dupla para visualização de dados
import matplotlib.pyplot as plt
import seaborn as sns

# Pacote para criar visualização dos valores ausentes
import missingno as msno

## Base original sem tratamento baixada do portal BNDES:
### Posição até 30/06/2026
https://www.bndes.gov.br/wps/portal/site/home/transparencia/centraldedownloads/!ut/p/z1/jZBBC4JAEIV_jddmatfKbmuZlhsKEdpeYiVTwdzYtX5_Up2kpDkMvOF778GAgBREIx9VIdtKNbLu9FFMT9wJvYBGyHHvEmSr2cbmvoN0SyB5AfhjGIL4xz8AiOH4BESvgsRrZAEfH-jOxUlI-0C0IV4HLLlNvXDsO-QDDJRsQRS1yt7_YE1G5gUInV9ynevRXXfnsm1vZmGhhZk0-VmZs-zWSOnCwm-mUpkW0j4Lt-shxSq-JnPDnl8eC3E!/dz/d5/L2dBISEvZ0FBIS9nQSEh/

In [5]:
# Carregando o DF
df_FG_Sebrae = pd.read_csv("Op_Garantia_FG_BNDES_Sebrae.csv", sep=';')

In [6]:
# Visualizando as 10 primeiras linhas do df
df_FG_Sebrae.head(10)

,nome_agente_financeiro,cnpj_cpf_cliente_mascarado,nome_cliente,porte_cliente,valor_credito,valor_garantido,valor_desembolsado,data_solicitacao_outorga,municipio_investimento,uf_investimento,municipio_sede_cliente,uf_sede_cliente
0,BTG PACTUAL,**.*45.846/0001-**,M.A. COMERCIO DIGITAL LTDA,Micro,"97722,01","78177,61","97722,01",2026-04-14,MIRASSOL,SP,MIRASSOL,SP
1,BTG PACTUAL,**.*87.844/0001-**,SEA TEXTIL LTDA,Pequena,"117266,41","93813,13","117266,41",2026-04-14,INDAIAL,SC,INDAIAL,SC
2,BTG PACTUAL,**.*04.711/0001-**,M J LTDA,Micro,"14999,61","11999,69","14999,61",2026-04-14,FRANCISCO MORATO,SP,FRANCISCO MORATO,SP
3,BTG PACTUAL,**.*07.697/0001-**,POUSADA VILLA BILAC LTDA,Micro,"17262,08","13809,66","17262,08",2026-04-14,BLUMENAU,SC,BLUMENAU,SC
4,BTG PACTUAL,**.*16.091/0001-**,PATRICIA PET SHOP LTDA,Micro,"10154,76","8123,81","10154,76",2026-04-15,CURITIBA,PR,CURITIBA,PR
5,BTG PACTUAL,**.*67.891/0001-**,JONATHAN OLIVEIRA CONSULTORIA IMOBILIARIA LTDA,Micro,"11716,88","9373,5","11716,88",2026-04-15,SAO PAULO,SP,SAO PAULO,SP
6,BTG PACTUAL,**.*40.853/0001-**,GOIVA ARQUITETURA LTDA,Pequena,"42962,22","34369,78","42962,22",2026-04-15,SAO PAULO,SP,SAO PAULO,SP
7,BTG PACTUAL,**.*69.176/0001-**,J. P. CONSTRUCOES LTDA,Pequena,"26624,2","21299,36","26624,2",2026-04-15,CUIABA,MT,CUIABA,MT
8,BTG PACTUAL,**.*15.757/0001-**,PAPILIO GIFTS COMERCIO LTDA,Micro,"8592,64","6874,11","8592,64",2026-04-16,CURITIBA,PR,CURITIBA,PR
9,BTG PACTUAL,**.*47.568/0001-**,SILVIO FELIX MEDEIROS FILHO LTDA,Micro,"10154,76","8123,81","10154,76",2026-04-16,PASSO FUNDO,RS,PASSO FUNDO,RS

In [7]:
# Numero (linhas e colunas)
df_FG_Sebrae.shape

(19302, 12)

In [8]:
# Informações
df_FG_Sebrae.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19302 entries, 0 to 19301
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   nome_agente_financeiro      19302 non-null  object
 1   cnpj_cpf_cliente_mascarado  19302 non-null  object
 2   nome_cliente                19302 non-null  object
 3   porte_cliente               19070 non-null  object
 4   valor_credito               19302 non-null  object
 5   valor_garantido             19302 non-null  object
 6   valor_desembolsado          19302 non-null  object
 7   data_solicitacao_outorga    19302 non-null  object
 8   municipio_investimento      19302 non-null  object
 9   uf_investimento             19302 non-null  object
 10  municipio_sede_cliente      19302 non-null  object
 11  uf_sede_cliente             19302 non-null  object
dtypes: object(12)
memory usage: 1.8+ MB

In [9]:
# Descrevendo os dados não numéricos
df_FG_Sebrae.describe(include = object)

,nome_agente_financeiro,cnpj_cpf_cliente_mascarado,nome_cliente,porte_cliente,valor_credito,valor_garantido,valor_desembolsado,data_solicitacao_outorga,municipio_investimento,uf_investimento,municipio_sede_cliente,uf_sede_cliente
count,19302,19302,19302,19070,19302,19302,19302,19302,19302,19302,19302,19302
unique,5,16529,18092,2,4751,4750,2876,105,2726,27,2726,27
top,BRADESCO,**.*23.100/0001-**,LTDA,Pequena,"103993,34","83194,67","100000,0",2025-09-17,SAO PAULO,SP,SAO PAULO,SP
freq,18873,5,7,18232,459,459,934,2095,1605,5154,1605,5154

### 1. Inicializar o repositório Git
Primeiro, você precisa inicializar um novo repositório Git no seu ambiente Colab.

In [13]:
!git init

Reinitialized existing Git repository in /content/.git/

### 2. Configurar o nome de usuário e e-mail
É importante configurar seu nome de usuário e e-mail, pois eles serão associados aos seus commits.

In [15]:
!git config --global user.email "lucascazane@gmail.com"
!git config --global user.name "Lucas Cazane"

### 3. Adicionar arquivos e fazer o primeiro commit
Adicione os arquivos do seu projeto ao repositório e faça o primeiro commit.

In [16]:
# Adicione todos os arquivos modificados ou novos
!git add .

# Faça o commit das alterações
!git commit -m "Primeiro commit inicial"

[master (root-commit) 5ee5a5c] Primeiro commit inicial
 22 files changed, 70393 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2026.08.10/13.24.58.373513.log
 create mode 100644 .config/logs/2026.08.10/13.25.25.328016.log
 create mode 100644 .config/logs/2026.08.10/13.25.43.233148.log
 create mode 100644 .config/logs/2026.08.10/13.26.03.888211.log
 create mode 100644 .config/logs/2026.08.10/13.26.18.998373.log
 create mode 100644 .config/logs/2026.08.10/13.26.19.834999.log
 create mode 100644 Op_Garantia_FG_BNDES_Sebrae.csv
 create mode 100755 sample_data/README.md
 create mode 100755 sample_data/anscombe.json
 create mode 100644 sample_data/california_housing_test.csv
 create mode 100644 sample_data/california_housing_train.csv
 create mode 100644 sample_data/mnist_test.csv
 create mode 100644 sample_data/mnist_train_small.csv

### 4. Adicionar o repositório remoto e fazer o push
Agora, adicione o repositório remoto (do GitHub, por exemplo) e envie suas alterações.

In [17]:
# Adicione o repositório remoto (substitua a URL pelo seu)
!git remote add origin https://github.com/LUCASCAZANE/Projeto1_Formacao_Continuada_Caixa_Verso.git

# Renomeie a branch principal (se necessário)
!git branch -M main

# Envie as alterações para o repositório remoto
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address